// GENERATED by ./scripts/build-skill-icons.py from scripts/skill-icons.txt.
// Add a skill there and re-run the script; do not edit this file.
//
// Keyed by the lowercased skill name. A skill with no entry gets no icon
// and no reserved space - see the note in skill-icons.txt.
//
// `hex` is the brand's official colour, published by Simple Icons.
// `dark: true` marks one too dark to read on a dark surface; SkillIcon
// falls back to the chip's own text colour for those.

export interface SkillIconEntry {
  slug: string
  hex: string
  dark?: boolean
}

export const SKILL_ICONS: Record<string, SkillIconEntry> = {
  'python': { slug: 'python', hex: '#3776AB' },
  'r': { slug: 'r', hex: '#276DC3' },
  'pandas': { slug: 'pandas', hex: '#150458', dark: true },
  'numpy': { slug: 'numpy', hex: '#013243', dark: true },
  'jupyter': { slug: 'jupyter', hex: '#F37626' },
  'tensorflow': { slug: 'tensorflow', hex: '#FF6F00' },
  'elasticsearch': { slug: 'elastic', hex: '#005571', dark: true },
  'grafana': { slug: 'grafana', hex: '#F46800' },
  'qgis': { slug: 'qgis', hex: '#589632' },
  'arcgis': { slug: 'arcgis', hex: '#2C7AC3' },
  'openstreetmap': { slug: 'openstreetmap', hex: '#7EBC6F' },
  'google earth': { slug: 'googleearth', hex: '#4285F4' },
  'microsoft excel': { slug: 'microsoftexcel', hex: '#217346' },
  'microsoft word': { slug: 'microsoftword', hex: '#2B579A' },
  'microsoft powerpoint': { slug: 'microsoftpowerpoint', hex: '#B7472A' },
  'microsoft teams': { slug: 'microsoftteams', hex: '#6264A7' },
  'microsoft outlook': { slug: 'microsoftoutlook', hex: '#0078D4' },
  'power bi': { slug: 'powerbi', hex: '#F2C811' },
  'power automate': { slug: 'powerautomate', hex: '#0066FF' },
  'google sheets': { slug: 'googlesheets', hex: '#34A853' },
  'google docs': { slug: 'googledocs', hex: '#4285F4' },
  'google drive': { slug: 'googledrive', hex: '#4285F4' },
  'google forms': { slug: 'googleforms', hex: '#7248B9' },
  'dropbox': { slug: 'dropbox', hex: '#0061FF' },
  'tableau': { slug: 'tableau', hex: '#E97627' },
  'looker': { slug: 'looker', hex: '#4285F4' },
  'google analytics': { slug: 'googleanalytics', hex: '#E37400' },
  'surveymonkey': { slug: 'surveymonkey', hex: '#00BF6F' },
  'typeform': { slug: 'typeform', hex: '#262627', dark: true },
  'jira': { slug: 'jira', hex: '#0052CC' },
  'confluence': { slug: 'confluence', hex: '#172B4D', dark: true },
  'trello': { slug: 'trello', hex: '#0052CC' },
  'asana': { slug: 'asana', hex: '#F06A6A' },
  'notion': { slug: 'notion', hex: '#000000', dark: true },
  'airtable': { slug: 'airtable', hex: '#18BFFF' },
  'clickup': { slug: 'clickup', hex: '#7B68EE' },
  'redmine': { slug: 'redmine', hex: '#B32024', dark: true },
  'miro': { slug: 'miro', hex: '#050038', dark: true },
  'zapier': { slug: 'zapier', hex: '#FF4F00' },
  'slack': { slug: 'slack', hex: '#4A154B', dark: true },
  'zoom': { slug: 'zoom', hex: '#0B5CFF' },
  'whatsapp': { slug: 'whatsapp', hex: '#25D366' },
  'telegram': { slug: 'telegram', hex: '#26A5E4' },
  'mailchimp': { slug: 'mailchimp', hex: '#FFE01B' },
  'quickbooks': { slug: 'quickbooks', hex: '#2CA01C' },
  'xero': { slug: 'xero', hex: '#13B5EA' },
  'odoo': { slug: 'odoo', hex: '#714B67' },
  'sap': { slug: 'sap', hex: '#0FAAFF' },
  'oracle': { slug: 'oracle', hex: '#F80000', dark: true },
  'salesforce': { slug: 'salesforce', hex: '#00A1E0' },
  'hubspot': { slug: 'hubspot', hex: '#FF7A59' },
  'stripe': { slug: 'stripe', hex: '#008CDD' },
  'figma': { slug: 'figma', hex: '#F24E1E' },
  'canva': { slug: 'canva', hex: '#00C4CC' },
  'adobe photoshop': { slug: 'adobephotoshop', hex: '#31A8FF' },
  'adobe illustrator': { slug: 'adobeillustrator', hex: '#FF9A00' },
  'adobe indesign': { slug: 'adobeindesign', hex: '#FF3366' },
  'javascript': { slug: 'javascript', hex: '#F7DF1E' },
  'typescript': { slug: 'typescript', hex: '#3178C6' },
  'react': { slug: 'react', hex: '#61DAFB' },
  'php': { slug: 'php', hex: '#777BB4' },
  'wordpress': { slug: 'wordpress', hex: '#21759B' },
  'postgresql': { slug: 'postgresql', hex: '#4169E1' },
  'mysql': { slug: 'mysql', hex: '#4479A1' },
  'mongodb': { slug: 'mongodb', hex: '#47A248' },
  'docker': { slug: 'docker', hex: '#2496ED' },
  'linux': { slug: 'linux', hex: '#FCC624' },
  'github': { slug: 'github', hex: '#181717', dark: true },
  'gitlab': { slug: 'gitlab', hex: '#FC6D26' },
}
